export const endpoints = {
  users: "/usuarios",
  services: "/servicios",
  categories: "/categorias",
  products: "/productos",
  uploads: "/uploads",
  suppliers: "/suplidores",
  ordenes: "/ordenes",
  detalleOrdenes: "/detalleOrdenes",
  configuraciones: "/configuraciones",
  entrada: "/entradas",
  facuracion: "/facturas",
  secuencial: "/secuencial",
  generica: "/generica",
};
