export const endpoints = {
  users: "/usuarios",
  services: "/servicios",
  categories: "/categorias",
  products: "/productos",
  uploads: "/uploads",
  suppliers: "/suplidores",
  ordenes: "/ordenes",
  detalleOrdenes: "/detalleOrdenes",
  configuraciones: "/configuraciones",
  entrada: "/entradas",
  facturacion: "/facturas",
  secuencial: "/secuencial",
  generica: "/generica",
  devoluciones: "/devoluciones",
  contratoDeServicio: "/contrato",
  tickets: "/tickets",
  desk: "/desk",
  request: "/request",
  message: "/message",
  report: "/reportes",
};
